=== Amarr7777/realEstate-XML/lab 5(real estate management XML)/realEstate.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tenants">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tenant" type="entityType" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="entityType">
        <xs:sequence>
            <xs:element name="id" type="xs:string" />
            <xs:element name="name" type="xs:string" />
            <xs:element name="contact" type="phoneType" />
            <xs:element name="email" type="emailType" />
            <xs:element name="rent" type="xs:decimal" />
            <xs:element name="securityDep" type="xs:decimal" />
            <xs:element name="type" type="tenantType" />
            <xs:element name="leaseTerm" type="xs:decimal" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="phoneType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+?\d[\d -]{8,12}\d"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tenantType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="residential"></xs:enumeration>
            <xs:enumeration value="commercial"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Amarr7777/realEstate-XML/lab 5(real estate management XML)/realEstate.XML
<?xml version="1.0" encoding="UTF-8"?>

<tenants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="realEstate.xsd">
    <tenant>
        <id>TA006</id>
        <name>Shanthanu</name>
        <contact>9458123531</contact>
        <email>gvdahnhuagfyg@gmail.com</email>
        <rent>25000</rent>
        <securityDep>45000</securityDep>
        <type>commercial</type>
        <leaseTerm>5</leaseTerm>
    </tenant>
    <tenant>
        <id>TA001</id>
        <name>shyam</name>
        <contact>9498123521</contact>
        <email>gvdahnhuagfyg@gmail.com</email>
        <rent>20000</rent>
        <securityDep>25000</securityDep>
        <type>commercial</type>
        <leaseTerm>5</leaseTerm>
    </tenant>
    <tenant>
        <id>TA008</id>
        <name>sharon</name>
        <contact>9454123521</contact>
        <email>gvdahnhuagfyg@yahoo.com</email>
        <rent>20000</rent>
        <securityDep>40000</securityDep>
        <type>residential</type>
        <leaseTerm>5</leaseTerm>
    </tenant>
</tenants>
